import {useEffect,useState} from 'react';
import {Activity,ArrowDown,ArrowUpRight,Building2,ChartNoAxesCombined,Database,Expand,Globe2,Layers3,Map,Radio,RotateCcw,ScanLine,SlidersHorizontal,SquareArrowOutUpRight,Wallet,Info,X} from 'lucide-react';
import MapView from './MapView';
import {MetricCard,TrendChart,FlatMix,TownRanking,PanelHeading} from './Charts';
import Transactions from './Transactions';
import {getJSON,queryString,number,money,monthLabel,titleCase} from './utils';

const defaults={start:'2024-01',end:'2024-12',town:'',flat_type:''};
function initialFilters(){const params=new URLSearchParams(location.search);return Object.fromEntries(Object.entries(defaults).map(([k,v])=>[k,params.has(k)?params.get(k):v]));}
export default function App(){
  const [meta,setMeta]=useState(null),[filters,setFilters]=useState(initialFilters),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[metric,setMetric]=useState('price'),[retry,setRetry]=useState(0),[expandedMap,setExpandedMap]=useState(false);
  useEffect(()=>{const controller=new AbortController();getJSON('/api/meta',controller.signal).then(setMeta).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[retry]);
  const filterKey=queryString(filters);
  useEffect(()=>{
    const controller=new AbortController();setLoading(true);setError('');
    history.replaceState(null,'','?'+filterKey+location.hash);
    const timer=setTimeout(()=>getJSON('/api/dashboard?'+filterKey,controller.signal).then(setData).catch(e=>{if(e.name!=='AbortError'){setData(null);setError(e.message);}}).finally(()=>{if(!controller.signal.aborted)setLoading(false);}),120);
    return()=>{controller.abort();clearTimeout(timer);};
  },[filterKey,retry]);
  useEffect(()=>{
    if(!expandedMap)return;
    const onKey=e=>{if(e.key==='Escape')setExpandedMap(false);};
    document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey);
  },[expandedMap]);
  const setFilter=(key,value)=>setFilters(f=>({...f,[key]:value}));
  const selectTown=town=>setFilter('town',town);
  const s=data?.summary;
  const flatLabel=filters.flat_type?titleCase(filters.flat_type):'All flat types';
  return <div className="app-shell">
    <a className="skip-link" href="#main">Skip to dashboard</a>
    <aside className="rail"><a className="brand-icon" href="#main" aria-label="HDB Atlas home"><Layers3 size={25}/></a><div className="rail-links"><a className="active" href="#main" title="Overview" aria-label="Overview"><Globe2 size={21}/></a><a href="#trends" title="Price trends" aria-label="Price trends"><ChartNoAxesCombined size={21}/></a><a href="#towns" title="Town comparison" aria-label="Town comparison"><Building2 size={21}/></a><a href="#transactions" title="Transactions" aria-label="Transactions"><Database size={20}/></a></div><a className="rail-info" href="#methodology" aria-label="Data and methodology"><Info size={20}/></a><span className="rail-line"/></aside>
    <div className="workspace"><header className="topbar"><a className="wordmark" href="#main">HDB<span className="brand-slash">/</span><b>ATLAS</b><span className="version">v1.0</span></a><nav aria-label="Main navigation"><a href="#main" className="active">Overview</a><a href="#transactions">Transactions</a><a href="#methodology">Data & methodology <ArrowUpRight size={12}/></a></nav><div className="system-status"><span className="live-dot"/>LOCAL DATA<span className="status-divider">/</span>SG</div></header>
    <main id="main"><section className="hero"><div><div className="eyebrow hero-eyebrow"><span className="tiny-line"/> SINGAPORE RESALE INTELLIGENCE</div><h1>The city.<br className="mobile-break"/> <span>Decoded.</span><span className="title-cursor">_</span></h1><p>Explore the patterns behind every postcode.</p></div><div className="hero-data"><div><Database size={14}/><b>{meta?number(meta.count):'—'}</b><span>TRANSACTIONS INDEXED</span></div><div className="coverage">{meta?`${monthLabel(meta.min_month)} — ${monthLabel(meta.max_month)}`:'Connecting to local data…'}<span className="tag magenta">5 DATASETS</span></div></div></section>
    <section className="filter-bar" aria-label="Dashboard filters"><div className="filter-caption"><SlidersHorizontal size={16}/><span>FILTER<br/>THE SIGNAL</span></div><label><span>FROM</span><input type="month" aria-label="From month" value={filters.start} min={meta?.min_month} max={meta?.max_month} onInput={e=>setFilter('start',e.currentTarget.value)}/></label><span className="date-arrow">→</span><label><span>TO</span><input type="month" aria-label="To month" value={filters.end} min={meta?.min_month} max={meta?.max_month} onInput={e=>setFilter('end',e.currentTarget.value)}/></label><label className="select-filter"><span>FLAT TYPE</span><select aria-label="Flat type" value={filters.flat_type} onChange={e=>setFilter('flat_type',e.target.value)}><option value="">All flat types</option>{meta?.flat_types.map(t=><option key={t} value={t}>{titleCase(t)}</option>)}</select></label><label className="select-filter town-select"><span>TOWN</span><select aria-label="Town" value={filters.town} onChange={e=>setFilter('town',e.target.value)}><option value="">All towns</option>{meta?.towns.map(t=><option key={t} value={t}>{titleCase(t)}</option>)}</select></label><button className="reset-button" onClick={()=>setFilters({...defaults})}><RotateCcw size={14}/><span>Reset</span></button></section>
    <div className="scope-line"><span><span className="small-dot"/>{filters.town?titleCase(filters.town):'Island-wide overview'}<i>/</i>{flatLabel}</span><span role="status">{loading?'SYNCING VIEW…':error?'QUERY ERROR':`${number(s?.count)} matching transactions`}</span></div>
    {error&&<div className="error-state" role="alert"><Info size={17}/>{error}<button className="text-button" onClick={()=>setRetry(r=>r+1)}>Retry</button></div>}
    <div className={'dashboard-content '+(loading?'is-loading':'')} aria-busy={loading}>
    <section className="metrics" aria-label="Market summary"><MetricCard label="MEDIAN RESALE PRICE" value={money(s?.price)} note="Nominal SGD · selected period" icon={Wallet} color="#3ee7d4" trend={data?.trend||[]} field="price"/><MetricCard label="MEDIAN PRICE / M²" value={money(s?.psm)} unit="/m²" note="Normalised by floor area" icon={ScanLine} color="#a88aff" trend={data?.trend||[]} field="psm"/><MetricCard label="TRANSACTIONS" value={number(s?.count)} note="Recorded resale transactions" icon={Activity} color="#f05eb9" trend={data?.trend||[]} field="count"/><MetricCard label="MEDIAN FLOOR AREA" value={number(s?.area,1)} unit="m²" note="Space behind the sale" icon={Expand} color="#eacc67" trend={data?.trend||[]} field="area"/></section>
    <section className={'panel map-panel '+(expandedMap?'map-expanded':'')} id="map"><PanelHeading eyebrow="01 / SPATIAL INTELLIGENCE" title="One island. Many markets."><div className="map-actions"><div className="segmented" aria-label="Map price measure"><button className={metric==='price'?'active':''} aria-pressed={metric==='price'} onClick={()=>setMetric('price')}>Resale price</button><button className={metric==='psm'?'active':''} aria-pressed={metric==='psm'} onClick={()=>setMetric('psm')}>Price / m²</button></div><button className="icon-button" aria-label={expandedMap?'Close expanded map':'Expand map'} onClick={()=>setExpandedMap(!expandedMap)}>{expandedMap?<X size={16}/>:<Expand size={16}/>}</button></div></PanelHeading><MapView towns={data?.towns||[]} selected={filters.town} onSelect={selectTown} metric={metric}/><div className="panel-foot map-foot"><span><Map size={13}/>Town-level aggregates · representative locations, not individual blocks</span><span><span className="small-dot"/>{data?.towns.length??0} towns in view</span></div></section>
    <div className="analysis-grid"><TrendChart data={data?.trend||[]} selected={filters.town}/><FlatMix data={data?.mix||[]} count={s?.count||0}/></div>
    <div className="insight-grid"><TownRanking towns={data?.towns||[]} selected={filters.town} onSelect={selectTown} metric={metric}/><section className="panel field-notes"><div className="eyebrow">SIGNAL / CONTEXT</div><div className="field-icon"><Radio size={28}/></div><h2>Look beyond<br/>the headline price<span>.</span></h2><p>Different homes tell different stories. Filter by flat type and compare price per square metre for a clearer view of each town.</p><div className="context-stat"><span>YOUR CURRENT LENS</span><strong>{flatLabel}</strong><small>{filters.start?monthLabel(filters.start):'Earliest'} → {filters.end?monthLabel(filters.end):'Latest'}</small></div><a href="#transactions" className="context-link">Explore the underlying transactions <ArrowUpRight size={17}/></a><div className="notes-grid" aria-hidden="true"/></section></div>
    </div>
    {!error&&<Transactions key={filterKey} filters={filters}/>}
    <section className="methodology" id="methodology"><details><summary><span><Info size={16}/> Know your data <span className="tag">METHODOLOGY & SOURCES</span></span><span className="details-hint">Expand <ArrowDown size={14}/></span></summary><div className="method-content"><div><h3>Historical records, not live listings</h3><p>All five local CSVs are included, covering {meta?`${monthLabel(meta.min_month)} to ${monthLabel(meta.max_month)}`:'1990–2025'}. February 2025 may be incomplete. Identical-looking transactions are preserved. Prices are nominal Singapore dollars and are not adjusted for inflation.</p><h3>How the figures are calculated</h3><p>Medians use individual matching transactions. Price per m² is calculated for each sale before taking the median. Changes in median prices can reflect differences in the homes sold, and are not a valuation forecast. Town comparisons share the date and flat-type filters and remain island-wide when a town is selected.</p></div><div><h3>A change in date basis</h3><p>Records through February 2012 use approval dates. From March 2012, records use registration dates. Remaining lease is shown where supplied; older sources do not contain this field.</p><h3>About the map</h3><p>Map geometry: <a href="https://data.gov.sg/datasets/d_4765db0e87b9c86336792efe8a1f7a66/view" target="_blank" rel="noreferrer">URA Master Plan 2019 planning areas</a>, under the <a href="https://data.gov.sg/open-data-licence" target="_blank" rel="noreferrer">Singapore Open Data Licence</a>. Planning areas are spatial context, not exact HDB town boundaries. Kallang represents Kallang/Whampoa; Downtown Core represents Central Area. Markers are polygon centroids, not block locations. Basemap: OpenStreetMap contributors.</p></div><div className="source-list"><h3>Imported source files</h3>{meta?.sources.map(source=><div key={source.file}><span>{source.file}</span><b>{number(source.rows)} rows</b></div>)}</div></div></details></section>
    <footer><div className="footer-brand"><Layers3 size={15}/> HDB<span>/</span>ATLAS <small>READ THE CITY.</small></div><span>BUILT ON REAL TRANSACTIONS<span className="footer-dot">·</span> SINGAPORE, SG <span className="small-dot"/></span></footer>
    </main></div>
  </div>;
}
