import {useState} from 'react';
import {AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,BarChart,Bar,Cell,PieChart,Pie} from 'recharts';
import {ArrowUpRight, TrendingUp, CircleDot, ChevronRight} from 'lucide-react';
import {money,number,compact,monthLabel,titleCase,colors} from './utils';

export function PanelHeading({eyebrow,title,children}){return <div className="panel-heading"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div>{children}</div>}
export function Empty({text='No transactions match these filters.'}){return <div className="empty-state"><CircleDot size={24}/><p>{text}</p><small>Try a wider date range or another flat type.</small></div>}
const tickStyle={fill:'#8b96b0',fontSize:10,fontFamily:'monospace'};
function ChartTooltip({active,payload,label,metric='price'}){
  if(!active||!payload?.length)return null;
  const row=payload[0].payload;
  return <div className="chart-tooltip"><b>{row.month?monthLabel(row.month):label}</b><strong>{metric==='count'?number(row.count):money(row[metric])}{metric==='psm'?' / m²':''}</strong><span>{number(row.count)} transactions</span></div>;
}
export function MetricCard({label,value,unit,note,icon:Icon,color,trend,field}){
  return <article className="metric-card" style={{'--accent':color}}><div className="metric-top"><span>{label}</span><Icon size={16}/></div><div className="metric-value">{value}<small>{unit}</small></div><div className="metric-bottom"><span>{note}</span><div className="sparkline" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><Area type="monotone" dataKey={field} stroke={color} fill={color} fillOpacity={.1} strokeWidth={1.5} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></div></article>;
}
export function TrendChart({data,selected}){
  const [metric,setMetric]=useState('price');
  return <section className="panel trend-panel" id="trends"><PanelHeading eyebrow="02 / TEMPORAL ANALYSIS" title="The market, over time"><div className="segmented" aria-label="Trend measure">{[['price','Price'],['psm','$/m²'],['count','Volume']].map(([key,label])=><button key={key} aria-pressed={key===metric} className={key===metric?'active':''} onClick={()=>setMetric(key)}>{label}</button>)}</div></PanelHeading><div className="chart-subtitle"><span className="small-dot"/>{selected?titleCase(selected):'All towns'} <span> / {metric==='count'?'Monthly transactions':metric==='psm'?'Median price per m²':'Median resale price'}{metric!=='count'?' · SGD':''}</span></div>{data.length?<div className="trend-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:12,right:15,bottom:0,left:0}}><defs><linearGradient id="trend-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3ee7d4" stopOpacity={.28}/><stop offset="100%" stopColor="#3ee7d4" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#222737" strokeDasharray="3 5"/><XAxis dataKey="month" tickFormatter={v=>data.length>24?v.slice(0,4):new Date(v+'-01').toLocaleDateString('en',{month:'short'})} tick={tickStyle} axisLine={false} tickLine={false} minTickGap={36} dy={9}/><YAxis tickFormatter={v=>metric==='count'?number(v):metric==='psm'?'$'+number(v):compact(v)} tick={tickStyle} axisLine={false} tickLine={false} width={60} domain={metric==='count'?[0,'auto']:['auto','auto']}/><Tooltip content={<ChartTooltip metric={metric}/>} cursor={{stroke:'#3ee7d4',strokeDasharray:'3 3'}}/><Area type="monotone" dataKey={metric} stroke="#3ee7d4" strokeWidth={2.3} fill="url(#trend-fill)" dot={data.length===1} activeDot={{r:5,fill:'#080b13',stroke:'#3ee7d4',strokeWidth:2}} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div>:<Empty/>}<div className="panel-foot"><TrendingUp size={13}/><span>Observed sale prices · not a quality-adjusted price index</span></div></section>;
}
export function FlatMix({data,count}){
  const [mode,setMode]=useState('mix');
  return <section className="panel mix-panel"><PanelHeading eyebrow="03 / FLAT PROFILE" title="What's changing hands"><button className="text-button" onClick={()=>setMode(mode==='mix'?'price':'mix')}>{mode==='mix'?'Compare prices':'View mix'}<ArrowUpRight size={14}/></button></PanelHeading>{!data.length?<Empty/>:mode==='mix'?<div className="mix-content"><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="count" nameKey="flat_type" innerRadius="70%" outerRadius="94%" paddingAngle={3} stroke="none" isAnimationActive={false}>{data.map((d,i)=><Cell key={d.flat_type} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={(v,name)=>[number(v)+' sales',titleCase(name)]} contentStyle={{background:'#151925',border:'1px solid #363d51',borderRadius:6,color:'#eef3ff'}} itemStyle={{color:'#eef3ff'}}/></PieChart></ResponsiveContainer><div className="donut-center"><b>{data.length}</b><span>FLAT TYPES</span></div></div><div className="mix-legend">{data.map((row,i)=><div key={row.flat_type}><span><i style={{background:colors[i%colors.length]}}/>{titleCase(row.flat_type)}</span><b>{row.count/count*100<.1?'<0.1':(row.count/count*100).toFixed(1)}<small>%</small></b></div>)}</div></div>:<div className="mix-prices">{data.map((row,i)=><div key={row.flat_type}><span>{titleCase(row.flat_type)}</span><div><i style={{width:row.price/Math.max(...data.map(d=>d.price))*100+'%',background:colors[i%colors.length]}}/></div><b>{compact(row.price)}</b></div>)}</div>}<div className="panel-foot"><CircleDot size={13}/><span>{mode==='mix'?'Share of transactions in the selected period':'Median resale price by flat type'}</span></div></section>;
}
export function TownRanking({towns,selected,onSelect,metric}){
  const [expanded,setExpanded]=useState(false);
  const key=metric==='psm'?'psm':'price';
  const sorted=[...towns].sort((a,b)=>b[key]-a[key]);
  const visible=expanded?sorted:sorted.slice(0,6);
  return <section className="panel ranking-panel" id="towns"><PanelHeading eyebrow="04 / TOWN COMPARISON" title="Across the island"><span className="tag">{towns.length} TOWNS</span></PanelHeading><div className="ranking-caption"><span>Ranked by median {metric==='psm'?'price / m²':'resale price'}</span><span>SGD</span></div>{!towns.length?<Empty/>:<div className="ranking-list">{visible.map((row,i)=><button className={'ranking-row '+(selected===row.town?'selected':'')} key={row.town} onClick={()=>onSelect(row.town===selected?'':row.town)} aria-pressed={selected===row.town}><span className="rank">{String(i+1).padStart(2,'0')}</span><div className="rank-info"><div><strong>{titleCase(row.town)}</strong><span>{number(row.count)} sales</span></div><div className="rank-track"><i style={{width:row[key]/sorted[0][key]*100+'%',background:i===0?'#f05eb9':i===1?'#a88aff':'#3ee7d4'}}/></div></div><b>{money(row[key])}</b><ChevronRight size={13}/></button>)}</div>}{towns.length>6&&<button className="ranking-more" onClick={()=>setExpanded(!expanded)}>{expanded?'Show top 6 towns':`Explore all ${towns.length} towns`}<ChevronRight size={14}/></button>}</section>;
}
